### ISSUE TITLE
build.sh and header file fixes for folks compiling this on Arch Linux x86_64 and gcc 12.x

### ISSUE THREAD

**Issue by trholding** [RuntimeRacer/Real-Time-Voice-Cloning#9]
build.sh fix for those who don't use conda or env
```
# Specific Python version in conda env, will fail if no specific version in your env:
if [[ ! -z $CONDA_PREFIX ]]
then
  cmake ../$BUILD_VARIANT/src -DPYTHON_EXECUTABLE=$CONDA_PREFIX/bin/python
else
#  cmake ../$BUILD_VARIANT/src -DPYTHON_EXECUTABLE=$CONDA_PYTHON_EXE
# The is the change:
cmake ../$BUILD_VARIANT/src -DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") -DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
fi
```

If build errors out with "error: ‘aligned_alloc’ is not a member of ‘std’; did you mean ‘aligned_union’?"

See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83662
See: https://stackoverflow.com/questions/29247065/compiler-cant-find-aligned-alloc-function

In wavernn.h change std::aligned_alloc to alligned_alloc

```
#ifdef __linux__
        weight = static_cast<float*>(aligned_alloc(32, sizeof(float)*wght.size()));
        rowIdx = static_cast<int*>(aligned_alloc(32, sizeof(int)*nGroups));
        colIdx = static_cast<int8_t*>(aligned_alloc(32, sizeof(int8_t)*nGroups));
#elif _WIN32
```

Ref: https://github.com/RuntimeRacer/Real-Time-Voice-Cloning/pull/7#issuecomment-1271774960

Really appreciate that you forked it and started improving on it. I'll be following your instructions. I don't have the juice to train. 

I am interested more in cpu inference. My specific interest is not voice cloning, but figuring out the concept on how to build a better low bitrate voice codec by making use of the voice fingerprint / vector along with mels from a degraded audio bitstream to get okay quality speech out. I'll elaborate on this later. I think the building blocks to that are here in this repo and few others. I'm a noob in neural networks, but I'll figure out. P.S. if you know of any cloud GPU services / hosting that are affordable, please let me know.

I'm interested in fixing the CLI tool as I need it. The GUI kind of hangs on record button press for both this fork and the origin - I'm still figuring out why.

**Comment by RuntimeRacer** [comment]
@trholding Hi, I just created a PR for your fixes. I did that quickly on my windows machine now where I can't compile the linux variant; therefore feel free to double-check and approve the PR in case you have the time.

**Comment by trholding** [comment]
Closing issue as it is solved now and works for me.
